<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-01T23:21:04 IST" name="Suite" finished-at="2024-02-01T23:21:04 IST" duration-ms="86">
    <groups>
    </groups>
    <test started-at="2024-02-01T23:21:04 IST" name="Test" finished-at="2024-02-01T23:21:04 IST" duration-ms="86">
      <class name="assertion.Soft_assertion_with_assertAll">
        <test-method signature="division()[pri:0, instance:assertion.Soft_assertion_with_assertAll@6a28ffa4]" started-at="2024-02-01T23:21:04 IST" name="division" finished-at="2024-02-01T23:21:04 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
!!! =====================Soft Assertio _All: division operation is not valid ===================== expected [5] but found [2],
!!! =====================Soft Assertio _All: multiply operation is not valid ===================== expected [19] but found [18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
!!! =====================Soft Assertio _All: division operation is not valid ===================== expected [5] but found [2],
!!! =====================Soft Assertio _All: multiply operation is not valid ===================== expected [19] but found [18]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at assertion.Soft_assertion_with_assertAll.division(Soft_assertion_with_assertAll.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- division -->
      </class> <!-- assertion.Soft_assertion_with_assertAll -->
      <class name="assertion.Hard_assertion">
        <test-method signature="division()[pri:0, instance:assertion.Hard_assertion@3e2e18f2]" started-at="2024-02-01T23:21:04 IST" name="division" finished-at="2024-02-01T23:21:04 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[!!! ===================== Hard_assertion : division operation is not valid ===================== expected [5] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: !!! ===================== Hard_assertion : division operation is not valid ===================== expected [5] but found [2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at assertion.Hard_assertion.division(Hard_assertion.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- division -->
      </class> <!-- assertion.Hard_assertion -->
      <class name="assertion.Soft_assertion_No_assertAll">
        <test-method signature="division()[pri:0, instance:assertion.Soft_assertion_No_assertAll@9353778]" started-at="2024-02-01T23:21:04 IST" name="division" finished-at="2024-02-01T23:21:04 IST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- division -->
      </class> <!-- assertion.Soft_assertion_No_assertAll -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
